export type Property = {
    property_id: number;
    name: string;
    notes: string | null;
    user_id: number;
    region: string | null;
    street: string | null;
    postal_code: string | null;
    city: string | null;
    house_number: string | null;
    country: string | null;
    timezone: string;
    customer_id: number | null;
    archive_at: Date | null;
    noti_incidents: integer;
    noti_tags: integer;
    noti_routes: integer;
    noti_mail: number | null;
    show_incidents: integer;
    show_routes: integer;
    show_time: integer;
    show_task: integer;
    show_docs: integer;
    wt_close_at: string | null;
    wt_disable_on: PropertyWTDisableOn;
    wt_pause: PropertyPauseType;
};

export type PropertyPauseType = 'none' | 'law' | '45' | '60';
export type PropertyWTDisableOn = { start: string; end: string }[];
